language: lisp

sudo: required

env:
    matrix:
        - LISP=abcl     # Armed Bear Common Lisp
        - LISP=allegro  # Allegro Common Lisp
        - LISP=ccl      # Clozure Common Lisp
        - LISP=clisp    # CLISP
        - LISP=sbcl     # Steel Bank Common Lisp

matrix:
    allow_failures:
        - env: LISP=allegro
        - env: LISP=clisp

install:
    # Install CL Travis Handler
    - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
    # Run the cl-transit tests using lisp-unit
    cl -e '(ql:quickload :cl-transit-tests)
           (unless (cl-transit-tests:run)
             (uiop:quit 1))'
